# Generated by Django 5.1.4 on 2025-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='firstname',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='lastname',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
