# Generated by Django 5.1.4 on 2025-01-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0003_remove_emailtemplate_name_emailtemplate_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_pending', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
